config/routes.rb
Qrforum::Application.routes.draw do
  resources :subscriptions

  resources :posts

  resources :walls

  match '/w/:code' => 'walls#show_by_code', :as => :show_by_code
  match '/qr/:code' => 'walls#qr_code', :as => :wall_qr
  match '/c/:id/:secret' => 'subscriptions#confirm', :as => :confirm_subscription
  match '/unsubscribe/:email' => 'subscriptions#unsubscribe_all', :constraints  => { :email => /[0-z%\.]+/ }, :as => :unsubscribe_all
  match '/unsubscribe/:id/:secret' => 'subscriptions#unsubscribe', :as => :unsubscribe
  

  root :to => 'walls#new'

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :wall
	validates :wall, :presence => true
	validates :body, :presence => true, :length => { :maximum => 400 }
	validates :signature, :presence => true, :length => { :maximum => 25 }
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
	belongs_to :wall, :counter_cache => true
	validates :wall, :presence => true
end

app/models/wall.rb
class Wall < ActiveRecord::Base
	has_many :posts
	has_many :subscriptions
	validates :title, :presence => true, :length => { :maximum => 75 }
	validates :code, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

	Pony.options = {
	  :via => :smtp,
	  :via_options => {
	    :address => 'smtp.sendgrid.net',
	    :port => '587',
	    :domain => 'heroku.com',
	    :user_name => ENV['SENDGRID_USERNAME'],
	    :password => ENV['SENDGRID_PASSWORD'],
	    :authentication => :plain,
	    :enable_starttls_auto => true
	  }
	}
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController


  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        wall = Wall.find params[:post][:wall_id]
        @post.wall.subscriptions.each do |sub|
          if sub.confirmed
            unsuburl = unsubscribe_url(sub.id, sub.secret)
            Pony.mail(:from => "QRum Robot <robot@qrum.se>",
                  :to => sub.email,
                  :subject =>  "New comment on " + wall.title,
                  :html_body => "<span style=\"font-family: sans-serif\">
                  New comment on <a href=\"#{show_by_code_url(wall.code)}\">#{wall.title}</a><br/>
                  <hr /><br />
                  #{@post.body}
                  <br /><br />
                  - #{@post.signature}
                  <hr /><br />
                  <a href=\"#{unsuburl}\">Stop emailing me about this!</a>
                  </span>
                  ")
          end
        end
            
        format.html { redirect_to show_by_code_url(@post.wall.code), 
                      notice: "Your comment has been posted to the wall. 
                      Don't forget to press the subscribe button below so that 
                      you'll know when someone responds!" }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    @subscription = Subscription.new
    @subscription.email = params[:email]
    @subscription.wall = Wall.find_by_id params[:id]
    @subscription.secret = SecureRandom.hex(8).force_encoding('UTF-8')[0,8]

    respond_to do |format|
      if @subscription.save

        confirm_url = confirm_subscription_url(:id => @subscription.id, :secret => @subscription.secret)
        Pony.mail(:from => "QRum Robot <robot@qrum.se>",
                  :to => @subscription.email,
                  :subject =>  "Confirm subscription: " + @subscription.wall.title,
                  :html_body => "<span style=\"font-family: sans-serif\"><h1>One step left!</h1>
                  <a href=\"#{confirm_url}\">Click here to confirm</a> that you really want 
                  to <br />receive updates to <b>#{@subscription.wall.title}.<br /><br />
                  - The little QRum robot
                  </span>
                  ")

        render json: @subscription, status: :created, location: @subscription
      else
        format.html { render action: "new" }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  def confirm
    @subscription = Subscription.find(params[:id])
    if @subscription and @subscription.secret == params[:secret]
      @subscription.confirmed = true
      @subscription.save
      qrurl = show_by_code_url(@subscription.wall.code)
      redirect_to qrurl, notice: 'Confirmed! You will now get email updates when comments are posted on this QRum.'
    else
      render :status => :forbidden
    end
  end

  # PUT /subscriptions/1
  # PUT /subscriptions/1.json
  def update
    @subscription = Subscription.find(params[:id])

    respond_to do |format|
      if @subscription.update_attributes(params[:subscription])
        format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  def unsubscribe
    @subscription = Subscription.find params[:id]
    if params[:secret] == @subscription.secret
      @subscription.destroy
    end
  end

  def unsubscribe_all
    subs = Subscription.where :email => params[:email]
    logger.info "email"+ params[:email]
    if subs.length > 0
      subs.each do |s|
        s.destroy
      end
    end
  end

end

app/controllers/walls_controller.rb
require 'prawn'

class WallsController < ApplicationController
  # GET /walls
  # GET /walls.json
  def index
    @walls = Wall.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @walls }
    end
  end

  def show_by_code
    
    @wall = Wall.find_by_code(params[:code])

    sess_key = 'visitor_counted_for_' + @wall.id.to_s
    if not session[sess_key]
      if @wall.views 
        @wall.views = @wall.views + 1
      else
        @wall.views = 1
      end
      @wall.save
      session[sess_key] = true
    end

    @latest_posts = Post.where(:wall_id => @wall.id)
    @post = Post.new(:wall_id => @wall.id)
    @post.wall = @wall

    respond_to do |format|
      format.html { render :action => :show }
      format.json { render json: @wall }
    end
  end

  def qr_code
    @wall = Wall.find_by_code params[:code]
  end

  # GET /walls/new
  # GET /walls/new.json
  def new
    @wall = Wall.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @wall }
    end
  end

  # POST /walls
  # POST /walls.json
  def create
    @wall = Wall.new(params[:wall])
    @wall.code = SecureRandom.hex(8).force_encoding('UTF-8')[0,8]

    respond_to do |format|
      if @wall.save
        format.html { redirect_to wall_qr_url(@wall.code, :format => :pdf), notice: 'Wall was successfully created.' }
        format.json { render json: @wall, status: :created, location: @wall }
      else
        format.html { render action: "new" }
        format.json { render json: @wall.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/walls_helper.rb
module WallsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%=h yield(:title) %></title>
  <%= stylesheet_link_tag "application" %>
  <link href='http://fonts.googleapis.com/css?family=Abel|Contrail+One|Reenie+Beanie' rel='stylesheet' type='text/css' />
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=320, initial-scale=1, user-scalable=yes" />
  <script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-125505-24']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</head>
<body>

<div id="content">
	<%= yield %>
</div>

<%= javascript_include_tag "application" %>
<script src="http://code.jquery.com/jquery-1.6.4.min.js"></script>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_field :body %>
  </div>
  <div class="field">
    <%= f.label :signature %><br />
    <%= f.text_field :signature %>
  </div>
  <div class="field">
    <%= f.label :wall_id %><br />
    <%= f.number_field :wall_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Body</th>
    <th>Signature</th>
    <th>Wall</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.body %></td>
    <td><%= post.signature %></td>
    <td><%= post.wall_id %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Body:</b>
  <%= @post.body %>
</p>

<p>
  <b>Signature:</b>
  <%= @post.signature %>
</p>

<p>
  <b>Wall:</b>
  <%= @post.wall_id %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/subscriptions/_form.html.erb
<%= form_for(@subscription) do |f| %>
  <% if @subscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

      <ul>
      <% @subscription.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :confirmed %><br />
    <%= f.check_box :confirmed %>
  </div>
  <div class="field">
    <%= f.label :secret %><br />
    <%= f.text_field :secret %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subscriptions/confirm.html.erb
<h1>Confirmed!</h1>
<p>You will now receive email updates to 
<b><%= @subscription.email %></b></p>

app/views/subscriptions/edit.html.erb
<h1>Editing subscription</h1>

<%= render 'form' %>

<%= link_to 'Show', @subscription %> |
<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/index.html.erb
<h1>Listing subscriptions</h1>

<table>
  <tr>
    <th>Email</th>
    <th>Confirmed</th>
    <th>Secret</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @subscriptions.each do |subscription| %>
  <tr>
    <td><%= subscription.email %></td>
    <td><%= subscription.confirmed %></td>
    <td><%= subscription.secret %></td>
    <td><%= link_to 'Show', subscription %></td>
    <td><%= link_to 'Edit', edit_subscription_path(subscription) %></td>
    <td><%= link_to 'Destroy', subscription, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Subscription', new_subscription_path %>

app/views/subscriptions/new.html.erb
<h1>New subscription</h1>

<%= render 'form' %>

<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @subscription.email %>
</p>

<p>
  <b>Confirmed:</b>
  <%= @subscription.confirmed %>
</p>

<p>
  <b>Secret:</b>
  <%= @subscription.secret %>
</p>


<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/unsubscribe.html.erb
<h1>Unsubscribed from <%= @subscription.wall.title %></h1><br />
If that is NOT enough, and you want unsubscribe <b><%= @subscription.email %></b> from ALL QRum subscriptions, <a href="<%= unsubscribe_all_path(URI::escape(CGI::escape(@subscription.email), '.')) %>" style="color:white">click here</a>.

app/views/subscriptions/unsubscribe_all.html.erb
You're now unsubscribed from everything!

app/views/walls/_form.html.erb
<%= form_for(@wall) do |f| %>
  <% if @wall.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wall.errors.count, "error") %> prohibited this wall from being saved:</h2>

      <ul>
      <% @wall.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field title">
    <%= f.text_area :title, :value => 'What do you think of this toilet?', :class => 'main_topic_field', :maxlength => 75 %>
  </div>
  <div class="actions">
    <%= image_submit_tag("start_button.png", :id => 'start_button') %>
  </div>
<% end %>

app/views/walls/edit.html.erb
<h1>Editing wall</h1>

<%= render 'form' %>

<%= link_to 'Show', @wall %> |
<%= link_to 'Back', walls_path %>

app/views/walls/index.html.erb
<h1>Listing walls</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Code</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @walls.each do |wall| %>
  <tr>
    <td><%= wall.title %></td>
    <td><%= wall.code %></td>
    <td><%= link_to 'Show', show_by_code_url(wall.code) %></td>
    <td><%= link_to 'Edit', edit_wall_path(wall) %></td>
    <td><%= link_to 'Destroy', wall, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Wall', new_wall_path %>

app/views/walls/new.html.erb
<% content_for :title, "QRum - forums hidden in QR codes." %>

<div id="big_box">
	<%= image_tag('qr_bg.png', :id => 'qr_bg') %>
	<%= image_tag('logo.png', :id => 'logo') %>

	<%= image_tag('big_box_top.png', :id => 'big_box_top_img') %>

	<%= render 'form' %>

	<p>QRum lets you create a digital forum in a physical place, any place, as long as you can stick a QR code on it!

	<p>Just type in the topic you want to discuss or a question you want answered above. This creates a <b>QRum</b>, a forum that can only be accessed via a unique QR code. Print the QR code and post it on a public toilet, inside a book, on a statue, under a bench, or the windshield of your car!</p>

	<p>Don't even think about it - it's totally free for everyone!</p>

	<p><b>- The QRum team</b></p>

	<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />
	<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />

</div>

app/views/walls/show.html.erb
<% content_for :title, @wall.title %>

<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

<div id="heading_box">
  <%= image_tag("box_top.png", :style => 'position: relative; left: -1px;width:100%') %>
  
  <h1 class="formheader"><%= @wall.title %></h1><br />
  <span class="stats"> 
    <%= pluralize @wall.views, 'scans' %> |
    <span id="subscribers_count">
      <%= pluralize @wall.subscriptions_count, 'subscribers' %>
    </span>
  </span>

  <%= image_tag("box_bottom.png", 
    :style => 'position: relative; left: -1px; top: 5px') %>
</div>

<button id="follow_button" class="dribbble smaller" 
        data-url="<%= subscriptions_path %>"
        data-id="<%= @wall.id %>">Subscribe via email</button>


<div id="posts">
  <%= image_tag("box_top.png", :style => 'position: relative; left: -1px;width:100%') %>
  <div id="posts_content">
    <% @latest_posts.each do |post| %>
    	<p class="signature"><%= post.signature %>:</p>
      <p class="body"><%= post.body %></p>
      <p class="time"><%= time_ago_in_words(post.created_at) %> ago</p>
      <hr />
    <% end %>
    <% if @latest_posts.length == 0 %>
    Nobody has written anything yet. Yay! You'll be the first one to write something!
    <% end %>

  </div>

    <%= form_for(@post) do |f| %>
    <input type="hidden" name="post[wall_id]" value="<%= @wall.id %>" />
    <% if @post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@post.errors.count, "error") %> 
        prohibited this post from being saved:</h2>
        <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="fields">
      <div class="body field">
        <%= f.text_area :body %>
      </div>
      <div class="signature field">
        <%= f.label :signature %>:
        <%= f.text_field :signature, :maxlength => 25 %>
      </div>
      <button class="dribbble">Post</button>
    </div>
  <% end %>

  <%= image_tag("box_bottom.png", 
    :style => 'position: relative; left: -1px; top: 5px') %>
</div>

<div id="bookmark_bar">
  Keep tabs on this discussion by bookmarking it!
  <div id="arrow">V</div>
</div>

<style>
#content {  width: 320px !important; }
</style>